outlandishideas/wpackagist

web/templates/search.twig

This PR makes the package name link to the plugin page on Wordpress.com, eg. `google-sitemap-generator` links to https://wordpress.org/plugins/google-sitemap-generator/

Add link to Wordpress.com Plugin Directory

---

src/Command/UpdateCommand.php

@tamlyn I've been trying to diagnose the bug where some plugins don't have new versions. Looking in the database at a couple of examples, I find packages where `last_committed < last_fetched`, but the newest versions are missing.
My theory is that we query the wordpress.org API too soon after the SVN repo is updated, so the new versions appear in SVN but not in the API response.
The change in this PR is to only update `last_fetched` if the `versions` JSON changes.
Does this make sense to you?

Refetch packages if they were last fetched within two hours of their most recent commit

---

src/Package/Plugin.php

There is an issue when using `dev-trunk` or requiring plugins that do not have a tagged version.
WordPress always puts such releases under the same URL even if it has been updated. But Composer has a URL cache, so it does not know that there is a new version available to download and will fetch from cache. 
For example, the URL might look like this:
```
https://downloads.wordpress.org/plugin/wp-core-media-widgets.zip
```
Because the URL never changes, running `composer install` will result in the packages being loaded from cache if it has downloaded an older version previously.
This PR introduces a change to how `dev-trunk`  URLs are handled. They will now have the `last_commited` timestamp to bypass the Composer cache. For example:
``` …
```

Fix update issue with dev-trunk packages

---

src/Command/UpdateCommand.php

It doesn't solve the underlying issue (why plugins sometimes don't update), but it does make it a bit less of a blocker for people.

Adds --name option to UpdateCommand, allowing for forced update

---

src/Command/UpdateCommand.php
src/Service/DoctrineServiceProvider.php
web/assets/css/style.css
web/index.php
web/templates/search.twig

Adds an /update action that runs the update command with the provided "name" parameter. Updates are limited by IP to 10 per hour.
Please check for security holes as we are dealing with client input!

Implements front end refresh button

---

web/templates/index.twig

Added installer-paths to composer.json example
The example is missing the installer paths argument otherwise the plugin gets installed straight into the `vendor` dir.

Added installer paths

---

.env
.gitignore
packages/Readme.md
src/Command/BuildCommand.php
src/Controller/MainController.php

JSON files are now served via a Symfony route and the source
files need not live in the local filesystem.
This should allow us to fix the build/serve process when deploying
to ECS and using EFS as a shared, persistent file store.

WPK-5 - 12-factor-ify package file location, using `PACKAGE_PATH` env var

---

src/Controller/MainController.php

This should hopefully fix the "Too many requests" errors when people update packages manually.
Symfony can also be configured to support upstream proxies (but you do need to know their IPs), which might be a better long-term solution.
https://symfony.com/doc/current/deployment/proxies.html

Attempt to fetch IP from upstream proxy

---

src/Service/Update.php

See https://github.com/outlandishideas/wpackagist/issues/342
Sample crash log from a full update when a delta one presumably clashed:
>   Cannot rename "/mount/efs/p.new" to "/mount/efs/p/".

Develop -> master: Temporarily make extra rebuilds a no-op until we can make them stable

---

web/assets/css/style.css

Currently, the code example overflows its' container. This adds the ability for the container to scroll.

Allow examples to scroll when overflowing container

---

src/Twig/PackageExtension.php
web/templates/search.twig

We don't need `formatCategory()` via Twig filter now we have Doctrine single table inheritance
mapping the classes

Simplify + tidy package type derivation

---

src/Entity/Package.php
src/Entity/PackageRepository.php
src/Service/Builder.php
src/Service/Update.php
src/Storage/Database.php
src/Storage/Filesystem.php
src/Storage/PackageStore.php

* Remove smaller provider groups from past years from `root` on update, fixes #381
* Deactivate individual provider groups too – this should ensure command outputs are consistent with `root` data and avoid any more serious unforeseen issues from the different references to groups going out of sync
* Related tidying

Keep provider group naming working across years

---

src/Entity/Package.php

Adds support for the `composer/installers` 2.x series, in addition to the 1.x series. This will allow folks to use plugins/themes via wpackagist even if another library requires `composer/installers` @ 2.x.
There are no WordPress-related breaking changes in the 2.x series, per [the changelog](https://github.com/composer/installers/releases/tag/v2.0.0).

add: Support `composer/installers:~2.0`

---

src/Entity/Package.php

In #420, support for `composer/installers` `v2` has been introduced. However, the constraints `~1.0 || ~2.0` don't match minor updates of `composer/installers`, e.g. [`1.12.0`](https://github.com/composer/installers/releases/tag/v1.12.0) or `2.1.0`. See https://jubianchi.github.io/semver-check/#/~1.0%20||%20~2.0/1.12.0.
This PR fixes it by replacing the tilde constraint with a caret constraint, similar to https://github.com/Rarst/release-belt/pull/46.

Allow updates to minor versions of `composer/installers`

---

config/services.yaml

Without this change, `ContainerRepositoryFactory` crashes passing only 2 args
to the repo.
Simply listing the class – which was previously excluded from auto-DI setup by the `exclude` rule below – is enough to get it the correct args because we have `autowire` on by default.

#442 – fix custom `RequestRepository` constructor

---

composer.json
config/services.yaml
src/Controller/MainController.php
src/Entity/RequestRepository.php

Including fixing the new service definition and explaining what's going on
in the repo class.

#442 – fix `MainController::update()`'s use of `RequestRepository` properly

---

src/Controller/MainController.php
web/templates/searchbar.twig

Previously, the logic would not capture exact matches (e.g., if you search for "woocommerce" you would get 130 pages of results but it doesn't look like it actually includes the exact match).  This is because it was doing a LIKE on "%woocommerce%" so not including the term itself.
Now, we explicitly check for that term in the beginning, middle, end of the results as well as for an exact match.  In addition, we have a smarter ordering where any exact match is at least listed first.  So now you don't have to scroll through hundreds of pages.
Also, drop the apparently-obsolete "active_only" parameter from search as it wasn't used anymore.

fix: better ordering for exact search matches

---

src/Service/Builder.php

Composer 2 introduced a few new properties that can be added to the packages.json response, among others `available-packages` or `available-package-patterns` see [Composer upgrade documentation](https://github.com/composer/composer/blob/main/UPGRADE-2.0.md#metadata-url).
Setting either of them allows anyone using the Composer repository to skip fetching the provider files if the required packages do not match the defined names/patterns, resulting in less request against WordPress Packagist.

Composer2: available-package-patterns

---

README.md
src/Controller/MainController.php
web/assets/css/style.css
web/assets/js/main.js

* [Try to make ad-hoc update calls more likely to succeed in multi-request edge cases](https://github.com/outlandishideas/wpackagist/commit/bbad4707c9a0ca441e993cfc16a1b2d0107161ea)
* [Lock refresh buttons; reduce accidental doubled-up package update calls](https://github.com/outlandishideas/wpackagist/commit/e250df67987526bb96c5a9e8c3a9635bb2995bfd)

Reduce on-demand update blips

---

src/Command/BuildCommand.php
src/Persistence/RetrySafeEntityManager.php

Move all the main package logic and database persistence into a retryable loop, and automatically recover without an error log up to once per command run.

Support `BuildCommand` retry if a duplicate constraint is hit

---

src/Persistence/RetrySafeEntityManager.php
src/Service/Update.php

It's not really clear to me why the EM is sometimes gone on a small % of these updates.
However the update and persist themselves should already have retries via the `EntityManagerInterface` injection, which already provides an object with a retry-safe version of those methods.
So I _think_ by process of elimination it's likely that the query itself (via a repo method which doesn't auto retry) is likely to be where it crashes.
This PR might help recover if that's right, and at a minimum should give us logs which allow us to confirm or deny that that's where the problem is is/when we get another similar crash.

Attempt to recover on single update if EntityManager was closed on find
